# Generated by Django 6.0.7 on 2026-07-23 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الصف')),
            ],
            options={
                'verbose_name': 'صف',
                'verbose_name_plural': 'الصفوف',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المادة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('due_date', models.DateField(verbose_name='تاريخ التنفيذ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تم التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
            ],
            options={
                'verbose_name': 'أجندة',
                'verbose_name_plural': 'الأجندات',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الناشر')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('parent_name', models.CharField(blank=True, help_text='يستخدم عند إرسال ولي الأمر', max_length=200, verbose_name='اسم ولي الأمر')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف ولي الأمر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('teacher', 'معلم'), ('student', 'طالب')], default='student', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف ولي الأمر')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='اسم ولي الأمر')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.class', verbose_name='الصف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('تأخير', 'تأخير'), ('تأديبية', 'ملاحظة تأديبية'), ('سلوك', 'ملاحظة سلوك'), ('تحصيل', 'ملاحظة تحصيل'), ('أخرى', 'أخرى')], default='أخرى', max_length=50, verbose_name='نوع الملاحظة')),
                ('content', models.TextField(verbose_name='محتوى الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('is_private', models.BooleanField(default=False, help_text='إذا كانت خاصة، ستظهر فقط لمدير المدرسة', verbose_name='خاصة بالإدارة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='كتب بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='school.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ملاحظة طالب',
                'verbose_name_plural': 'ملاحظات الطلاب',
            },
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_time', models.TimeField(verbose_name='وقت المغادرة')),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='وقت العودة')),
                ('reason', models.TextField(verbose_name='سبب المغادرة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='approved', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('leave_date', models.DateField(auto_now_add=True, verbose_name='تاريخ المغادرة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='موافق بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='school.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إذن مغادرة',
                'verbose_name_plural': 'أذونات المغادرة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جداً'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, verbose_name='المستوى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='school.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'مستوى طالب',
                'verbose_name_plural': 'مستويات الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200, verbose_name='اسم الامتحان')),
                ('total_students', models.PositiveIntegerField(verbose_name='عدد الطلاب')),
                ('passed_count', models.PositiveIntegerField(verbose_name='عدد الناجحين')),
                ('failed_count', models.PositiveIntegerField(verbose_name='عدد الراسبين')),
                ('pass_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة النجاح')),
                ('fail_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الرسوب')),
                ('success_reasons', models.TextField(blank=True, verbose_name='أسباب النجاح')),
                ('fail_reasons', models.TextField(blank=True, verbose_name='أسباب الرسوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.class', verbose_name='الصف')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'تحليل امتحان',
                'verbose_name_plural': 'تحليلات الامتحانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='school.class', verbose_name='الصفوف')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='school.subject', verbose_name='المواد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمون',
            },
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='كتب بواسطة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'ملاحظة معلم',
                'verbose_name_plural': 'ملاحظات المعلمين',
            },
        ),
    ]
