# Generated by Django 6.0.7 on 2026-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plain_password',
            field=models.CharField(blank=True, help_text='تظهر لمدير المدرسة فقط', max_length=100, verbose_name='كلمة المرور'),
        ),
    ]
