# Generated by Django 6.0.7 on 2026-07-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_profile_role_userpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('lesson_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت الحصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'رابط حصة',
                'verbose_name_plural': 'روابط الحصص',
                'ordering': ['lesson_datetime', 'created_at'],
            },
        ),
    ]
