# Generated by Django 6.0.7 on 2026-07-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_lessonlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlink',
            name='url',
            field=models.URLField(max_length=500, verbose_name='الرابط'),
        ),
    ]
