# Generated by Django 6.0.7 on 2026-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_lessonlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlink',
            name='url',
            field=models.TextField(verbose_name='الرابط'),
        ),
    ]
