# Generated by Django 6.0.7 on 2026-07-28 22:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_lessonlink_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLateness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاريخ التأخير')),
                ('notes', models.TextField(blank=True, help_text='سبب التأخير والإجراء المتبع', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateness', to='school.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تأخير طالب',
                'verbose_name_plural': 'تأخيرات الطلاب',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_lateness_per_day')],
            },
        ),
    ]
