# Generated by Django 6.0.7 on 2026-07-29 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_studentlateness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المدرسة (عربي)')),
                ('name_en', models.CharField(max_length=200, verbose_name='اسم المدرسة (إنجليزي)')),
                ('principal_name', models.CharField(max_length=200, verbose_name='اسم المدير')),
                ('national_number', models.CharField(max_length=50, verbose_name='رقم المدرسة الوطني')),
            ],
            options={
                'verbose_name': 'بيانات المدرسة',
                'verbose_name_plural': 'بيانات المدرسة',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('الجميع', 'الجميع'), ('زمري', 'زمري')], max_length=50, verbose_name='نوع الاجتماع')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('day', models.CharField(max_length=50, verbose_name='اليوم')),
                ('time', models.TimeField(verbose_name='الساعة')),
                ('place', models.CharField(choices=[('غرفة المعلمين', 'غرفة المعلمين'), ('غرفة الإدارة', 'غرفة الإدارة')], max_length=100, verbose_name='مكان الاجتماع')),
                ('goals', models.TextField(verbose_name='أهداف الاجتماع')),
                ('minutes', models.TextField(verbose_name='محضر الاجتماع')),
                ('meeting_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الاجتماع')),
                ('all_teachers', models.BooleanField(default=False, verbose_name='جميع المعلمين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, to='school.teacher', verbose_name='المعلمون الحاضرون')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اجتماع',
                'verbose_name_plural': 'الاجتماعات',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
