# Generated by Django 6.0.7 on 2026-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_schoolinfo_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
    ]
