# Generated by Django 6.0.7 on 2026-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_schoolinfo_latitude_schoolinfo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='ministry_logo',
            field=models.URLField(blank=True, default='', help_text='رابط مباشر للصورة', null=True, verbose_name='رابط شعار الوزارة'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='school_logo',
            field=models.URLField(blank=True, default='', help_text='رابط مباشر للصورة (مثال: من Google Drive أو ImgBB)', null=True, verbose_name='رابط شعار المدرسة'),
        ),
    ]
