# Generated by Django 6.0.7 on 2026-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_schoolinfo_latitude_schoolinfo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='ministry_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار الوزارة'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار المدرسة'),
        ),
    ]
