# Generated by Django 6.0.7 on 2026-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_schoolinfo_ministry_logo_schoolinfo_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='ministry_logo',
            field=models.URLField(blank=True, default='', help_text='رابط مباشر للصورة', max_length=500, null=True, verbose_name='رابط شعار الوزارة'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_logo',
            field=models.URLField(blank=True, default='', help_text='رابط مباشر للصورة (مثال: من Google Drive أو ImgBB)', max_length=500, null=True, verbose_name='رابط شعار المدرسة'),
        ),
    ]
