# Generated by Django 6.0.7 on 2026-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_schoolinfo_ministry_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, help_text='مثال: بكالوريوس، ماجستير، دكتوراه', max_length=200, verbose_name='المؤهل العلمي'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, help_text='مثال: رياضيات، فيزياء، لغة عربية', max_length=200, verbose_name='التخصص'),
        ),
    ]
