# Generated by Django 6.0.7 on 2026-07-30 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_teacher_qualification_teacher_specialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='id_number',
            field=models.CharField(blank=True, help_text='رقم هوية المعلم الوطني', max_length=50, verbose_name='رقم الهوية'),
        ),
        migrations.CreateModel(
            name='SupervisorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الزيارة')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('subject_area', models.CharField(blank=True, max_length=200, verbose_name='المبحث')),
                ('lesson_topic', models.CharField(blank=True, max_length=300, verbose_name='موضوع الدرس')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='الصف')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='الشعبة')),
                ('supervisor_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المشرف')),
                ('recommendations', models.TextField(blank=True, verbose_name='توصيات المشرف')),
                ('admin_followup', models.TextField(blank=True, verbose_name='متابعة الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_visits', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'زيارة مشرف',
                'verbose_name_plural': 'زيارات المشرفين',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
