# Generated by Django 6.0.7 on 2026-07-31 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('visit_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الزيارة')),
                ('subject_area', models.CharField(blank=True, max_length=200, verbose_name='المبحث')),
                ('lesson_topic', models.CharField(blank=True, max_length=300, verbose_name='موضوع الدرس')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='الصف')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='الشعبة')),
                ('content_teaching', models.TextField(blank=True, verbose_name='المحتوى التعليمي')),
                ('teaching_strategies', models.TextField(blank=True, verbose_name='استراتيجيات التدريس')),
                ('evaluation_strategies', models.TextField(blank=True, verbose_name='استراتيجيات التقويم')),
                ('other_matters', models.TextField(blank=True, verbose_name='أمور أخرى')),
                ('plans_followup', models.TextField(blank=True, verbose_name='متابعة الخطط وتنفيذها')),
                ('attendance_followup', models.TextField(blank=True, verbose_name='متابعة الدوام المدرسي')),
                ('committees_followup', models.TextField(blank=True, verbose_name='متابعة تفعيل اللجان المدرسية')),
                ('violence_policy', models.TextField(blank=True, verbose_name='الالتزام بسياسة الحد من العنف')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات للمعلم')),
                ('principal_sign_date', models.DateField(blank=True, null=True, verbose_name='تاريخ توقيع المدير')),
                ('teacher_receipt_date', models.DateField(blank=True, null=True, verbose_name='تاريخ استلام المعلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_visits', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'زيارة إشرافية',
                'verbose_name_plural': 'الزيارات الإشرافية',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
