# Generated by Django 6.0.7 on 2026-07-31 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_inspectionvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='تاريخ الحضور')),
                ('lesson', models.CharField(blank=True, max_length=200, verbose_name='الحصة')),
                ('notes', models.TextField(blank=True, help_text='مثال: تم، لم يتم، أو أي ملاحظة أخرى', verbose_name='الملاحظات')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='تم إرسال التذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_program_entries', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'برنامج زيارة',
                'verbose_name_plural': 'برنامج الزيارات',
                'ordering': ['-visit_date', 'teacher__full_name'],
            },
        ),
    ]
