# Generated by Django 6.0.7 on 2026-08-01 08:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_visitprogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('تفوق دراسي', 'تفوق دراسي'), ('اجتهاد ومثابرة', 'اجتهاد ومثابرة'), ('سلوك ممتاز', 'سلوك ممتاز'), ('حضور مميز', 'حضور مميز'), ('مشاركة فعالة', 'مشاركة فعالة'), ('موهبة وإبداع', 'موهبة وإبداع'), ('أخرى', 'أخرى')], default='تفوق دراسي', max_length=50, verbose_name='نوع الشهادة')),
                ('custom_text', models.CharField(blank=True, help_text='سطر يظهر في الشهادة تحت سبب التقدير', max_length=300, verbose_name='نص إضافي')),
                ('cert_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الإصدار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أصدرها')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='school.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'شهادة تقدير',
                'verbose_name_plural': 'شهادات التقدير',
                'ordering': ['-cert_date', '-created_at'],
            },
        ),
    ]
