# Generated by Django 6.0.7 on 2026-08-01 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at'], 'verbose_name': 'شهادة تقدير', 'verbose_name_plural': 'شهادات التقدير'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cert_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cert_type',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='custom_text',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_year',
            field=models.CharField(default='', max_length=20, verbose_name='سنة التدريس'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='class_name',
            field=models.CharField(default='', max_length=100, verbose_name='الصف'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم مربي الصف'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أصدرها'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='principal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم مدير المدرسة'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student_name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم الطالب'),
        ),
        migrations.AddField(
            model_name='class',
            name='guardian',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_class', to='school.teacher', verbose_name='مربي الصف'),
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nominated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رشّحه')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='school.student', verbose_name='الطالب')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='school.class', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'ترشيح متفوق',
                'verbose_name_plural': 'ترشيحات المتفوقين',
                'ordering': ['student_class__name', 'student__full_name'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='nomination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='school.nomination', verbose_name='الترشيح'),
        ),
    ]
