# Generated by Django 6.0.7 on 2026-08-01 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField(verbose_name='تاريخ الغياب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='school.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'غياب طالب',
                'verbose_name_plural': 'غياب الطلاب',
                'ordering': ['-absence_date', 'student__full_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'absence_date'), name='unique_student_absence_day')],
            },
        ),
    ]
