# Generated by Django 6.0.7 on 2026-08-01 20:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_studentabsence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_count', models.PositiveIntegerField(default=6, verbose_name='عدد الحصص')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='بداية الحصة الأولى')),
                ('period_minutes', models.PositiveIntegerField(default=45, verbose_name='مدة الحصة (دقيقة)')),
                ('break_minutes', models.PositiveIntegerField(default=10, verbose_name='مدة الاستراحة (دقيقة)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات البرنامج',
                'verbose_name_plural': 'إعدادات البرنامج',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='اليوم')),
                ('period', models.PositiveIntegerField(verbose_name='رقم الحصة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='school.class', verbose_name='الصف')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='school.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='school.teacher', verbose_name='المعلم')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة')),
            ],
            options={
                'verbose_name': 'حصة في البرنامج',
                'verbose_name_plural': 'البرنامج اليومي',
                'ordering': ['day', 'period', 'student_class__name'],
                'constraints': [models.UniqueConstraint(fields=('day', 'period', 'student_class'), name='unique_schedule_cell')],
            },
        ),
    ]
