# Generated by Django 6.0.7 on 2026-08-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_schedulesettings_scheduleentry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='unique_schedule_cell',
        ),
        migrations.DeleteModel(
            name='ScheduleSettings',
        ),
        migrations.DeleteModel(
            name='ScheduleEntry',
        ),
    ]
