# Generated by Django 6.0.7 on 2026-08-01 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_remove_scheduleentry_unique_schedule_cell_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='اليوم')),
                ('period', models.PositiveIntegerField(verbose_name='رقم الحصة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='school.class', verbose_name='الصف')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='school.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='school.teacher', verbose_name='المعلم')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة')),
            ],
            options={
                'verbose_name': 'حصة في الجدول',
                'verbose_name_plural': 'الجدول اليومي للمعلمين',
                'ordering': ['day', 'period'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'day', 'period'), name='unique_teacher_schedule_cell')],
            },
        ),
    ]
