# Generated by Django 6.0.7 on 2026-08-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_teacherscheduleentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الدخول')),
                ('last_reset', models.DateTimeField(blank=True, null=True, verbose_name='آخر تصفير')),
            ],
            options={
                'verbose_name': 'عداد دخول الطلاب',
                'verbose_name_plural': 'عداد دخول الطلاب',
            },
        ),
    ]
