# Generated by Django 6.0.7 on 2026-08-02 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_logincounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_disease', models.BooleanField(default=False, verbose_name='مرض مزمن')),
                ('chronic_disease_details', models.CharField(blank=True, max_length=500, verbose_name='تفاصيل المرض المزمن')),
                ('regular_medication', models.BooleanField(default=False, verbose_name='أدوية منتظمة')),
                ('medication_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الدواء')),
                ('has_allergy', models.BooleanField(default=False, verbose_name='حساسية')),
                ('allergy_drugs', models.BooleanField(default=False, verbose_name='حساسية أدوية')),
                ('allergy_food', models.BooleanField(default=False, verbose_name='حساسية أطعمة')),
                ('allergy_dust', models.BooleanField(default=False, verbose_name='حساسية غبار')),
                ('allergy_other', models.CharField(blank=True, max_length=300, verbose_name='حساسية أخرى')),
                ('condition_asthma', models.BooleanField(default=False, verbose_name='الربو')),
                ('condition_diabetes', models.BooleanField(default=False, verbose_name='السكري')),
                ('condition_epilepsy', models.BooleanField(default=False, verbose_name='الصرع')),
                ('condition_heart', models.BooleanField(default=False, verbose_name='مشاكل القلب')),
                ('condition_hearing', models.BooleanField(default=False, verbose_name='ضعف السمع')),
                ('condition_vision', models.BooleanField(default=False, verbose_name='ضعف البصر')),
                ('condition_none', models.BooleanField(default=False, verbose_name='لا يوجد حالات صحية')),
                ('needs_glasses', models.BooleanField(default=False, verbose_name='نظارات طبية')),
                ('special_care', models.BooleanField(default=False, verbose_name='رعاية صحية خاصة')),
                ('special_care_details', models.CharField(blank=True, max_length=500, verbose_name='تفاصيل الرعاية الخاصة')),
                ('emergency_instructions', models.TextField(blank=True, verbose_name='تعليمات خاصة للطبيب أو المدرسة')),
                ('lives_with', models.CharField(choices=[('parents', 'الأب والأم'), ('father', 'الأب فقط'), ('mother', 'الأم فقط'), ('relative', 'أحد الأقارب'), ('other', 'أخرى')], default='parents', max_length=50, verbose_name='يعيش مع')),
                ('lives_with_other', models.CharField(blank=True, max_length=200, verbose_name='محدد أخرى')),
                ('family_members_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد أفراد الأسرة')),
                ('siblings_in_school_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الإخوة في المدرسة')),
                ('study_difficulties', models.BooleanField(default=False, verbose_name='صعوبات تؤثر على الدراسة')),
                ('study_difficulties_details', models.CharField(blank=True, max_length=500, verbose_name='تفاصيل الصعوبات')),
                ('support_academic', models.BooleanField(default=False, verbose_name='دعم أكاديمي')),
                ('support_psychological', models.BooleanField(default=False, verbose_name='دعم نفسي')),
                ('support_social', models.BooleanField(default=False, verbose_name='دعم اجتماعي')),
                ('support_none', models.BooleanField(default=False, verbose_name='لا يحتاج دعم')),
                ('has_study_place', models.BooleanField(default=False, verbose_name='مكان مخصص للمذاكرة')),
                ('has_smartphone', models.BooleanField(default=False, verbose_name='هاتف ذكي')),
                ('has_computer', models.BooleanField(default=False, verbose_name='جهاز حاسوب')),
                ('has_internet', models.BooleanField(default=False, verbose_name='اتصال بالإنترنت')),
                ('has_no_device', models.BooleanField(default=False, verbose_name='لا يتوفر أي منها')),
                ('participates_activities', models.BooleanField(default=False, verbose_name='أنشطة رياضية/ثقافية خارج المدرسة')),
                ('family_special_conditions', models.BooleanField(default=False, verbose_name='ظروف خاصة للأسرة')),
                ('family_special_conditions_details', models.CharField(blank=True, max_length=500, verbose_name='تفاصيل الظروف الخاصة')),
                ('contact_counselor', models.BooleanField(default=False, verbose_name='التواصل مع المرشد التربوي')),
                ('contact_method', models.CharField(choices=[('phone', 'اتصال هاتفي'), ('whatsapp', 'واتساب'), ('sms', 'رسالة نصية')], default='', max_length=20, verbose_name='أفضل وسيلة تواصل')),
                ('strengths', models.TextField(blank=True, verbose_name='أبرز نقاط القوة')),
                ('difficulties_notes', models.TextField(blank=True, verbose_name='أبرز الصعوبات')),
                ('subjects_need_support', models.TextField(blank=True, verbose_name='المواد التي يحتاج دعم')),
                ('suggestions', models.TextField(blank=True, verbose_name='اقتراحات لخدمة الطالب')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعبئة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='school.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'مسح صحي واجتماعي',
                'verbose_name_plural': 'المسح الصحي والاجتماعي',
                'ordering': ['student__full_name'],
            },
        ),
    ]
