# Generated by Django 6.0.7 on 2026-08-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_studentsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsurvey',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('phone', 'اتصال هاتفي'), ('whatsapp', 'واتساب'), ('sms', 'رسالة نصية')], default='', max_length=20, verbose_name='أفضل وسيلة تواصل'),
        ),
    ]
