# Generated by Django 6.0.7 on 2026-08-04 19:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_alter_studentsurvey_contact_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026/2027', max_length=20, verbose_name='العام الدراسي')),
                ('number', models.CharField(max_length=50, verbose_name='رقم الوارد')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('letter_type', models.CharField(blank=True, max_length=100, verbose_name='النوع')),
                ('source_entity', models.CharField(blank=True, max_length=200, verbose_name='الجهة الصادرة')),
                ('attachments', models.CharField(blank=True, max_length=200, verbose_name='المرفقات')),
                ('subject', models.TextField(blank=True, verbose_name='الموضوع')),
                ('file_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
            ],
            options={
                'verbose_name': 'وارد',
                'verbose_name_plural': 'سجل الوارد',
                'ordering': ['date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(max_length=50, verbose_name='رقم الكتاب')),
                ('book_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الكتاب')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='اسم الدائرة الصادر اليها الكتاب')),
                ('subject', models.TextField(blank=True, verbose_name='الموضوع')),
                ('issuing_entity', models.CharField(blank=True, max_length=200, verbose_name='الجهة المحررة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
            ],
            options={
                'verbose_name': 'صادر',
                'verbose_name_plural': 'سجل الصادر',
                'ordering': ['book_date', 'book_number'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='رابط واتساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to='school.class', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'رابط واتساب للصف',
                'verbose_name_plural': 'روابط واتساب الصفوف',
                'ordering': ['student_class__name', 'id'],
            },
        ),
    ]
