# Generated by Django 6.0.7 on 2026-08-05 11:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_incomingletter_outgoingletter_whatsappgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ المتابعة')),
                ('prep_done', models.BooleanField(default=False, verbose_name='التحضير متابَع')),
                ('prep_notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات التحضير')),
                ('marks_done', models.BooleanField(default=False, verbose_name='العلامات متابَعة')),
                ('marks_notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات العلامات')),
                ('follow_done', models.BooleanField(default=False, verbose_name='المتابعة متابَعة')),
                ('follow_notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات المتابعة')),
                ('plans_done', models.BooleanField(default=False, verbose_name='الخطط متابَعة')),
                ('plans_notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات الخطط')),
                ('absence_done', models.BooleanField(default=False, verbose_name='دفتر الغياب متابَع')),
                ('absence_notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات دفتر الغياب')),
                ('general_notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'متابعة معلم',
                'verbose_name_plural': 'متابعة المعلمين',
                'ordering': ['-follow_date', 'teacher__full_name'],
            },
        ),
    ]
