# Generated by Django 6.0.7 on 2026-08-05 22:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_teacherfollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciprocalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الزيارة')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='رقم الحصة')),
                ('positive_points', models.TextField(blank=True, verbose_name='أبرز النقاط الإيجابية')),
                ('development_points', models.TextField(blank=True, verbose_name='أبرز النقاط التي تحتاج إلى تطوير')),
                ('agreement', models.TextField(blank=True, verbose_name='ما تم الاتفاق عليه مع المعلم المزار')),
                ('completed', models.BooleanField(default=False, verbose_name='اكتملت المتابعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_filled_by_teacher', to='school.teacher', verbose_name='أُدخلت بواسطة')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciprocal_visits_as_host', to='school.teacher', verbose_name='المعلم المزار')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciprocal_visits', to='school.class', verbose_name='الصف')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciprocal_visits_as_visitor', to='school.teacher', verbose_name='المعلم الزائر')),
            ],
            options={
                'verbose_name': 'زيارة تبادلية',
                'verbose_name_plural': 'الزيارات التبادلية',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
