# Generated by Django 6.0.7 on 2026-08-06 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_reciprocalvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='اسم الطالب')),
                ('student_class', models.CharField(max_length=100, verbose_name='الصف')),
                ('sending_school', models.CharField(max_length=200, verbose_name='اسم المدرسة الباعثة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
            ],
            options={
                'verbose_name': 'لا مانع',
                'verbose_name_plural': 'لا مانع',
                'ordering': ['-created_at'],
            },
        ),
    ]
