# Generated by Django 6.0.7 on 2026-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='plain_password',
            field=models.CharField(blank=True, help_text='تظهر لمدير المدرسة فقط', max_length=100, verbose_name='كلمة المرور'),
        ),
    ]
