# Generated by Django 6.0.7 on 2026-08-15 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_teacher_plain_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianSummons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summons_date', models.DateField(verbose_name='تاريخ الاستدعاء')),
                ('summons_text', models.TextField(verbose_name='نص الاستدعاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أصدر بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summons', to='school.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'استدعاء ولي أمر',
                'verbose_name_plural': 'استدعاءات أولياء الأمور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(verbose_name='تاريخ الحادثة')),
                ('incident_facts', models.TextField(verbose_name='وقائع الحادثة')),
                ('delivery_method', models.CharField(choices=[('direct', 'تسليم مباشر للطالب'), ('guardian', 'تسليم لولي الأمر')], default='direct', max_length=20, verbose_name='طريقة تسليم الإنذار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أصدر بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='school.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إنذار طالب',
                'verbose_name_plural': 'إنذارات الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
