# Generated by Django 6.0.7 on 2026-08-21 21:05

from django.db import migrations


def delete_parent_messages(apps, schema_editor):
    Message = apps.get_model('school', 'Message')
    Message.objects.filter(sender__isnull=True).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_guardiansummons_studentwarning'),
    ]

    operations = [
        migrations.RunPython(delete_parent_messages, noop),
        migrations.RemoveField(
            model_name='message',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_phone',
        ),
    ]
