# Generated by Django 6.0.7 on 2026-08-24 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_remove_message_parent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم البرنامج')),
                ('version_label', models.CharField(blank=True, max_length=100, verbose_name='تسمية الإصدار')),
                ('academic_year', models.CharField(blank=True, max_length=50, verbose_name='العام الدراسي')),
                ('semester', models.CharField(blank=True, max_length=50, verbose_name='الفصل الدراسي')),
                ('days', models.JSONField(default=list, verbose_name='أيام الدوام')),
                ('periods', models.JSONField(default=list, verbose_name='الحصص')),
                ('breaks', models.JSONField(blank=True, default=list, verbose_name='الاستراحة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'فعّال'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('hard_score', models.FloatField(blank=True, null=True, verbose_name='نسبة الالتزام بالقيود الصلبة')),
                ('soft_score', models.FloatField(blank=True, null=True, verbose_name='نسبة الالتزام بالقيود الناعمة')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='school.scheduleplan', verbose_name='نسخة من')),
            ],
            options={
                'verbose_name': 'برنامج أسبوعي',
                'verbose_name_plural': 'البرامج الأسبوعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hard', 'إلزامي'), ('soft', 'تفضيلي')], default='hard', max_length=10, verbose_name='النوع')),
                ('code', models.CharField(max_length=60, verbose_name='الرمز')),
                ('label', models.CharField(max_length=200, verbose_name='الوصف')),
                ('enabled', models.BooleanField(default=True, verbose_name='مفعل')),
                ('weight', models.FloatField(default=1.0, verbose_name='الوزن')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='معاملات')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='school.scheduleplan', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'شرط',
                'verbose_name_plural': 'الشروط والقيود',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='اليوم')),
                ('period', models.PositiveIntegerField(verbose_name='رقم الحصة')),
                ('fixed', models.BooleanField(default=False, verbose_name='مثبتة')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='لون')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='school.class', verbose_name='الصف')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='school.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='school.teacher', verbose_name='المعلم')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='school.scheduleplan', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'حصة في البرنامج',
                'verbose_name_plural': 'حصص البرنامج',
                'ordering': ['day', 'period'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'day', 'period'), name='unique_plan_cell'), models.UniqueConstraint(fields=('plan', 'teacher', 'day', 'period'), name='unique_plan_teacher_cell'), models.UniqueConstraint(fields=('plan', 'student_class', 'day', 'period'), name='unique_plan_class_cell')],
            },
        ),
        migrations.CreateModel(
            name='FixedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='اليوم')),
                ('period', models.PositiveIntegerField(verbose_name='رقم الحصة')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_lessons', to='school.class', verbose_name='الصف')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_lessons', to='school.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_lessons', to='school.teacher', verbose_name='المعلم')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_lessons', to='school.scheduleplan', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'حصة مثبتة',
                'verbose_name_plural': 'الحصص المثبتة',
                'constraints': [models.UniqueConstraint(fields=('plan', 'day', 'period'), name='unique_fixed_lesson_cell')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='اليوم')),
                ('period', models.PositiveIntegerField(verbose_name='رقم الحصة')),
                ('available', models.BooleanField(default=True, verbose_name='متاح')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='school.scheduleplan', verbose_name='البرنامج')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'تفريغ معلم',
                'verbose_name_plural': 'تفريغ المعلمين',
                'constraints': [models.UniqueConstraint(fields=('plan', 'teacher', 'day', 'period'), name='unique_teacher_availability')],
            },
        ),
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_periods', models.PositiveIntegerField(default=1, verbose_name='عدد الحصص أسبوعيًا')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='school.scheduleplan', verbose_name='البرنامج')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='school.class', verbose_name='الصف/الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='school.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'نصيب مادة',
                'verbose_name_plural': 'أنصبة المواد',
                'constraints': [models.UniqueConstraint(fields=('plan', 'teacher', 'subject', 'student_class'), name='unique_teaching_load')],
            },
        ),
    ]
