# Generated by Django 6.0.7 on 2026-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_scheduleplan_scheduleconstraint_scheduleentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingload',
            name='semester',
            field=models.CharField(blank=True, choices=[('', 'كل الفصول'), ('الأول', 'الفصل الأول'), ('الثاني', 'الفصل الثاني')], default='', max_length=20, verbose_name='الفصل الدراسي'),
        ),
    ]
