# Generated by Django 6.0.7 on 2026-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_teachingload_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconstraint',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='schedule_constraints', to='school.class', verbose_name='الصفوف'),
        ),
        migrations.AddField(
            model_name='scheduleconstraint',
            name='scope',
            field=models.CharField(choices=[('all', 'الكل'), ('teachers', 'معلمون محددون'), ('classes', 'صفوف محددة')], default='all', max_length=10, verbose_name='النطاق'),
        ),
        migrations.AddField(
            model_name='scheduleconstraint',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='schedule_constraints', to='school.teacher', verbose_name='المعلمون'),
        ),
    ]
