# Generated by Django 6.0.7 on 2026-08-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_scheduleconstraint_classes_scheduleconstraint_scope_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleentry',
            name='unique_plan_cell',
        ),
    ]
