# Generated by Django 6.1.1 on 2026-09-15 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_student_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_title', models.CharField(blank=True, max_length=240, verbose_name='الوحدة')),
                ('unit_order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب الوحدة')),
                ('lesson_order', models.PositiveSmallIntegerField(verbose_name='ترتيب الدرس')),
                ('title', models.CharField(max_length=240, verbose_name='عنوان الدرس')),
                ('start_printed_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='أول صفحة مطبوعة')),
                ('end_printed_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='آخر صفحة مطبوعة')),
                ('start_pdf_page', models.PositiveSmallIntegerField(verbose_name='أول صفحة PDF')),
                ('end_pdf_page', models.PositiveSmallIntegerField(verbose_name='آخر صفحة PDF')),
            ],
            options={
                'verbose_name': 'درس منهاج',
                'verbose_name_plural': 'دروس المنهاج',
                'ordering': ['source', 'unit_order', 'lesson_order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumAssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='تشغيل مساعد المنهاج')),
                ('daily_question_limit', models.PositiveSmallIntegerField(default=15, verbose_name='الحد اليومي لكل طالب')),
                ('source_only', models.BooleanField(default=True, verbose_name='الإجابة من المصادر المعتمدة فقط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات مساعد المنهاج',
                'verbose_name_plural': 'إعدادات مساعد المنهاج',
            },
        ),
        migrations.CreateModel(
            name='CurriculumSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.PositiveSmallIntegerField(verbose_name='الصف')),
                ('term', models.PositiveSmallIntegerField(default=1, verbose_name='الفصل')),
                ('subject_code', models.CharField(choices=[('arabic', 'اللغة العربية'), ('math', 'الرياضيات'), ('science', 'العلوم'), ('english', 'اللغة الإنجليزية')], max_length=30, verbose_name='رمز المادة')),
                ('subject_name', models.CharField(max_length=120, verbose_name='اسم المادة')),
                ('title', models.CharField(max_length=240, verbose_name='اسم المصدر')),
                ('edition', models.CharField(blank=True, max_length=120, verbose_name='الطبعة أو الإصدار')),
                ('original_filename', models.CharField(max_length=300, verbose_name='اسم الملف الأصلي')),
                ('source_sha256', models.CharField(max_length=64, unique=True, verbose_name='بصمة الملف SHA-256')),
                ('page_count', models.PositiveSmallIntegerField(verbose_name='عدد صفحات PDF')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('google_drive_file_id', models.CharField(blank=True, max_length=200, verbose_name='معرّف الملف في Google Drive')),
                ('google_drive_url', models.URLField(blank=True, max_length=600, verbose_name='رابط الملف في Google Drive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مصدر منهاج',
                'verbose_name_plural': 'مصادر المنهاج',
                'ordering': ['grade_level', 'term', 'subject_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_page_number', models.PositiveSmallIntegerField(verbose_name='رقم صفحة PDF')),
                ('printed_page_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='رقم الصفحة المطبوع')),
                ('text', models.TextField(blank=True, verbose_name='النص المستخرج')),
                ('normalized_text', models.TextField(blank=True, verbose_name='النص المفهرس')),
                ('visual_summary', models.TextField(blank=True, verbose_name='وصف المحتوى البصري')),
                ('needs_visual_review', models.BooleanField(default=False, verbose_name='تحتاج مراجعة بصرية')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='school.curriculumlesson')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='school.curriculumsource')),
            ],
            options={
                'verbose_name': 'صفحة منهاج',
                'verbose_name_plural': 'صفحات المنهاج',
                'ordering': ['source', 'pdf_page_number'],
            },
        ),
        migrations.AddField(
            model_name='curriculumlesson',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.curriculumsource'),
        ),
        migrations.CreateModel(
            name='CurriculumConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان المحادثة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأت في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر رسالة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_conversations', to='school.student')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='school.curriculumlesson')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='school.curriculumsource')),
            ],
            options={
                'verbose_name': 'محادثة منهاج',
                'verbose_name_plural': 'محادثات المنهاج',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumAnswerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_question', models.CharField(max_length=500, verbose_name='السؤال الموحد')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='المراجع')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='الأسئلة المقترحة')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='مرات الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر استخدام')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_cache', to='school.curriculumlesson')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_cache', to='school.curriculumsource')),
            ],
            options={
                'verbose_name': 'إجابة منهاج محفوظة',
                'verbose_name_plural': 'إجابات المنهاج المحفوظة',
            },
        ),
        migrations.CreateModel(
            name='CurriculumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'الطالب'), ('assistant', 'المساعد')], max_length=20, verbose_name='صاحب الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='المراجع')),
                ('estimated_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='الرموز المقدّرة')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة بالمللي ثانية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school.curriculumconversation')),
            ],
            options={
                'verbose_name': 'رسالة مساعد المنهاج',
                'verbose_name_plural': 'رسائل مساعد المنهاج',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='curr_msg_convo_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='curriculumsource',
            index=models.Index(fields=['grade_level', 'term', 'status'], name='curr_src_grade_term_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumpage',
            index=models.Index(fields=['source', 'lesson', 'pdf_page_number'], name='curr_page_lesson_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumpage',
            constraint=models.UniqueConstraint(fields=('source', 'pdf_page_number'), name='unique_curriculum_pdf_page'),
        ),
        migrations.AddConstraint(
            model_name='curriculumlesson',
            constraint=models.UniqueConstraint(fields=('source', 'lesson_order'), name='unique_curriculum_lesson_order'),
        ),
        migrations.AddConstraint(
            model_name='curriculumanswercache',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('source', 'lesson', 'normalized_question'), name='uniq_curr_cache_lesson'),
        ),
        migrations.AddConstraint(
            model_name='curriculumanswercache',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', True)), fields=('source', 'normalized_question'), name='uniq_curr_cache_book'),
        ),
    ]
