# Generated by Django 6.1.1 on 2026-09-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_curriculum_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='عنوان الفيديو')),
                ('youtube_video_id', models.CharField(max_length=20, verbose_name='معرّف فيديو يوتيوب')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر للطلاب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='school.curriculumlesson')),
            ],
            options={
                'verbose_name': 'فيديو درس منهاج',
                'verbose_name_plural': 'فيديوهات دروس المنهاج',
                'ordering': ['lesson', 'position', 'pk'],
                'indexes': [models.Index(fields=['lesson', 'is_active', 'position'], name='curr_video_lesson_idx')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'youtube_video_id'), name='uniq_curr_lesson_youtube_video')],
            },
        ),
    ]
