# Generated by Django 6.1.1 on 2026-09-29 06:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_studentlevel_assessment_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCommitteeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('item', models.CharField(max_length=200, verbose_name='بند المشتريات')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='القيمة')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
            ],
            options={
                'verbose_name': 'مشتريات اللجنة الاجتماعية',
                'verbose_name_plural': 'مشتريات اللجنة الاجتماعية',
                'ordering': ['year', 'month', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='social_expense_valid_month'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='social_expense_positive')],
            },
        ),
        migrations.CreateModel(
            name='SocialCommitteePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200, verbose_name='اسم المعلم وقت الدفع')),
                ('year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ المدفوع')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_committee_payments', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'مدفوعات اللجنة الاجتماعية',
                'verbose_name_plural': 'مدفوعات اللجنة الاجتماعية',
                'ordering': ['year', 'month', 'teacher_name'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'year', 'month'), name='unique_social_teacher_month'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='social_payment_valid_month'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='social_payment_nonnegative')],
            },
        ),
    ]
