# Generated by Django 6.0.7 on 2026-08-13 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0032_teacher_plain_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدرس')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('published', 'منشور'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('review_note', models.TextField(blank=True, help_text='سبب الرفض إن وُجد', verbose_name='ملاحظة المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_lessons', to='school.class', verbose_name='الصف')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_lessons', to='school.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_lessons', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'درس مفتوح',
                'verbose_name_plural': 'دروس التعلم المفتوح',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المورد')),
                ('resource_type', models.CharField(choices=[('video', 'فيديو'), ('presentation', 'عرض تقديمي'), ('exercise', 'تمرين'), ('homework', 'واجب'), ('summary', 'ملخص'), ('quiz', 'اختبار'), ('activity', 'نشاط'), ('lesson', 'درس'), ('link', 'رابط'), ('reading', 'قراءة')], max_length=20, verbose_name='النوع')),
                ('url', models.TextField(verbose_name='الرابط')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='وصف مختصر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='open_learning.learninglesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'مورد تعليمي',
                'verbose_name_plural': 'الموارد التعليمية',
                'ordering': ['created_at'],
            },
        ),
    ]
