# Generated by Django 6.0.7 on 2026-08-13 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglesson',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ توليد المحتوى الذكي'),
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='ai_payload',
            field=models.JSONField(blank=True, default=dict, help_text='أقسام المحتوى المولّد بالذكاء الاصطناعي', verbose_name='المحتوى الذكي'),
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='ai_review_note',
            field=models.TextField(blank=True, verbose_name='ملاحظة مراجعة المحتوى الذكي'),
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='ai_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجع المحتوى الذكي'),
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='ai_status',
            field=models.CharField(choices=[('none', 'بدون محتوى ذكي'), ('pending', 'بانتظار مراجعة المعلم'), ('approved', 'معتمد')], default='none', max_length=20, verbose_name='حالة المحتوى الذكي'),
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='content_hash',
            field=models.CharField(blank=True, help_text='بصمة الصف+المادة+العنوان+الوصف لتجنب إعادة التوليد', max_length=64, verbose_name='بصمة المحتوى'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإضافة الذكية'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='أُضيف بواسطة الذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='language',
            field=models.CharField(choices=[('ar', 'عربي'), ('en', 'إنجليزي'), ('other', 'أخرى')], default='ar', max_length=10, verbose_name='اللغة'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='relevance_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درجة الملاءمة'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المصدر'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('archived', 'مؤرشف')], default='approved', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'فيديو'), ('presentation', 'عرض تقديمي'), ('exercise', 'تمرين'), ('homework', 'واجب'), ('summary', 'ملخص'), ('quiz', 'اختبار'), ('activity', 'نشاط'), ('lesson', 'درس'), ('link', 'رابط'), ('reading', 'قراءة'), ('image', 'صورة'), ('simulation', 'محاكاة'), ('experiment', 'تجربة')], max_length=20, verbose_name='النوع'),
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=50, verbose_name='العملية')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='المزوّد')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='النموذج')),
                ('success', models.BooleanField(default=True, verbose_name='نجحت')),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('estimated_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='الرموز المقدّرة')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة بالمللي ثانية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='open_learning.learninglesson', verbose_name='الدرس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل استخدام الذكاء الاصطناعي',
                'verbose_name_plural': 'سجل استخدام الذكاء الاصطناعي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningResourceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان المصدر')),
                ('url', models.TextField(verbose_name='الرابط')),
                ('normalized_url', models.CharField(max_length=500, unique=True, verbose_name='رابط موحّد')),
                ('resource_type', models.CharField(choices=[('video', 'فيديو'), ('presentation', 'عرض تقديمي'), ('exercise', 'تمرين'), ('homework', 'واجب'), ('summary', 'ملخص'), ('quiz', 'اختبار'), ('activity', 'نشاط'), ('lesson', 'درس'), ('link', 'رابط'), ('reading', 'قراءة'), ('image', 'صورة'), ('simulation', 'محاكاة'), ('experiment', 'تجربة')], max_length=20, verbose_name='النوع')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المصدر')),
                ('language', models.CharField(choices=[('ar', 'عربي'), ('en', 'إنجليزي'), ('other', 'أخرى')], default='ar', max_length=10, verbose_name='اللغة')),
                ('relevance_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='درجة الملاءمة')),
                ('grade_level', models.CharField(blank=True, max_length=100, verbose_name='الصف الدراسي')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='وصف مختصر')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('archived', 'مؤرشف')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='أُضيف بواسطة الذكاء الاصطناعي')),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإضافة الذكية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أضافه')),
            ],
            options={
                'verbose_name': 'مصدر في مكتبة التعلم',
                'verbose_name_plural': 'مكتبة مصادر التعلم',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='learningresource',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_links', to='open_learning.learningresourcelibrary', verbose_name='المصدر المركزي'),
        ),
    ]
