# Generated by Django 6.0.7 on 2026-08-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0002_learninglesson_ai_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_json', models.TextField(blank=True, help_text='رمز الوصول ورمز التحديث مشفّران (موقّعان) ولا يظهران في الكود أو نظام الملفات', verbose_name='بيانات الرمز المشفّرة')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية رمز الوصول')),
                ('scope', models.TextField(blank=True, verbose_name='النطاق المصرّح به')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'رمز Google Drive',
                'verbose_name_plural': 'رموز Google Drive',
            },
        ),
    ]
