# Generated by Django 6.0.7 on 2026-08-25 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0003_googledrivetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أضافه'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='file_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='اسم الملف'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع الملف'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='معرّف ملف Google Drive'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='google_drive_url',
            field=models.TextField(blank=True, verbose_name='رابط Google Drive'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='source_kind',
            field=models.CharField(blank=True, choices=[('link', 'رابط خارجي'), ('google_drive', 'Google Drive')], default='link', max_length=20, verbose_name='مصدر المورد'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='storage_provider',
            field=models.CharField(blank=True, choices=[('', '—'), ('google_drive', 'Google Drive')], default='', max_length=20, verbose_name='مزوّد التخزين'),
        ),
    ]
