# Generated by Django 6.0.7 on 2026-08-25 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0004_learningresource_created_by_and_more'),
        ('school', '0039_remove_fixedlesson_unique_fixed_lesson_cell_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='بداية الأسبوع')),
                ('week_end', models.DateField(verbose_name='نهاية الأسبوع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('completed', 'مكتملة'), ('sent', 'مرسلة للمتابعة'), ('reviewed', 'تمت مراجعتها'), ('needs_improvement', 'تحتاج تحسين')], default='draft', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='school.class', verbose_name='الصف')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'خطة أسبوعية',
                'verbose_name_plural': 'الخطط الأسبوعية',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('الأحد', 'الأحد'), ('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس')], max_length=20, verbose_name='يوم الأسبوع')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('lesson_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان الدرس')),
                ('objectives', models.TextField(blank=True, verbose_name='الأهداف')),
                ('homework', models.TextField(blank=True, verbose_name='الواجبات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_days', to='open_learning.learninglesson', verbose_name='الدرس')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='school.subject', verbose_name='المادة')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='open_learning.weeklyplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'يوم في الخطة الأسبوعية',
                'verbose_name_plural': 'أيام الخطة الأسبوعية',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('needs_improvement', 'تحتاج تحسين'), ('approved', 'معتمدة')], default='needs_improvement', max_length=20, verbose_name='النتيجة')),
                ('general_note', models.TextField(blank=True, verbose_name='ملاحظة عامة')),
                ('reviewed_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
                ('weekly_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='open_learning.weeklyplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'مراجعة الخطة الأسبوعية',
                'verbose_name_plural': 'مراجعات الخطط الأسبوعية',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(max_length=100, verbose_name='المحور')),
                ('indicator', models.TextField(verbose_name='مؤشر الجودة')),
                ('is_met', models.BooleanField(default=False, verbose_name='متحقق')),
                ('needs_improvement', models.BooleanField(default=False, verbose_name='يحتاج تحسين')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='open_learning.weeklyplanreview', verbose_name='المراجعة')),
            ],
            options={
                'verbose_name': 'مؤشر جودة',
                'verbose_name_plural': 'مؤشرات الجودة',
                'ordering': ['order'],
            },
        ),
    ]
