# Generated by Django 6.0.7 on 2026-08-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0005_weeklyplan_weeklyplanday_weeklyplanreview_and_more'),
        ('school', '0039_remove_fixedlesson_unique_fixed_lesson_cell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_plans', to='school.class', verbose_name='الصف')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_plans', to='school.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_plans', to='school.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'خطة معلم مرفوعة',
                'verbose_name_plural': 'خطط المعلمين المرفوعة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPlanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=300, verbose_name='اسم الملف')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الملف')),
                ('google_drive_file_id', models.CharField(blank=True, max_length=200, verbose_name='معرّف ملف Google Drive')),
                ('google_drive_url', models.TextField(blank=True, verbose_name='رابط الملف في Drive')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='open_learning.teacherplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'ملف خطة معلم',
                'verbose_name_plural': 'ملفات خطط المعلمين',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
