# Generated by Django 6.0.7 on 2026-08-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0006_teacherplan_teacherplanfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='delivery_mode',
            field=models.CharField(choices=[('presence', 'وجاهي'), ('tasks', 'مهمات')], default='presence', help_text='وجاهي: دروس اعتيادية، مهمات: تعليم عن بُعد بمهمات يومية', max_length=20, verbose_name='نمط التسليم'),
        ),
        migrations.AddField(
            model_name='weeklyplanday',
            name='task',
            field=models.TextField(blank=True, help_text='تُعبّأ في نمط المهمات', verbose_name='مهمة تعليمية'),
        ),
        migrations.AddField(
            model_name='weeklyplanday',
            name='task_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='موعد تسليم المهمة'),
        ),
        migrations.AlterField(
            model_name='weeklyplanday',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات (روابط مصادر التعليم المفتوح)'),
        ),
    ]
