# Generated by Django 6.0.7 on 2026-08-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0007_weeklyplan_delivery_mode_weeklyplanday_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyplan',
            name='delivery_mode',
        ),
        migrations.AddField(
            model_name='weeklyplanday',
            name='delivery_mode',
            field=models.CharField(choices=[('presence', 'وجاهي'), ('tasks', 'مهمات')], default='presence', help_text='وجاهي: دروس اعتيادية، مهمات: تعليم عن بُعد بمهمات يومية', max_length=20, verbose_name='نمط التسليم لليوم'),
        ),
    ]
