# Generated by Django 6.0.7 on 2026-08-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0008_remove_weeklyplan_delivery_mode_and_more'),
        ('school', '0040_noobjection_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninglesson',
            name='student_class',
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='student_classes',
            field=models.ManyToManyField(blank=True, related_name='learning_lessons', to='school.class', verbose_name='الصفوف'),
        ),
    ]
