# Generated by Django 6.1.1 on 2026-09-07 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_radio_rls(apps, schema_editor, enabled):
    if schema_editor.connection.vendor != 'postgresql':
        return
    entry = apps.get_model('open_learning', 'SchoolRadioEntry')
    radio_file = apps.get_model('open_learning', 'SchoolRadioFile')
    models_to_secure = [
        entry,
        entry._meta.get_field('presenters').remote_field.through,
        entry._meta.get_field('participants').remote_field.through,
        radio_file,
    ]
    action = 'ENABLE' if enabled else 'DISABLE'
    for model in models_to_secure:
        table = schema_editor.quote_name(model._meta.db_table)
        schema_editor.execute(f'ALTER TABLE {table} {action} ROW LEVEL SECURITY')


def enable_radio_rls(apps, schema_editor):
    set_radio_rls(apps, schema_editor, True)


def disable_radio_rls(apps, schema_editor):
    set_radio_rls(apps, schema_editor, False)


class Migration(migrations.Migration):

    dependencies = [
        ('open_learning', '0012_full_learning_enhancements'),
        ('school', '0050_student_admin_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRadioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='تاريخ الإذاعة')),
                ('title', models.CharField(default='الإذاعة المدرسية', max_length=200, verbose_name='عنوان الإذاعة')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='موضوع الإذاعة')),
                ('category', models.CharField(choices=[('general', 'عامة'), ('national', 'وطنية'), ('religious', 'دينية'), ('educational', 'تعليمية'), ('health', 'صحية'), ('environmental', 'بيئية'), ('social', 'اجتماعية'), ('other', 'أخرى')], default='general', max_length=20, verbose_name='نوع المناسبة')),
                ('additional_presenters', models.TextField(blank=True, verbose_name='أسماء مقدّمين إضافيين')),
                ('additional_participants', models.TextField(blank=True, verbose_name='أسماء مشاركين إضافيين')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('ai_word', models.JSONField(blank=True, default=dict, verbose_name='الكلمة المولّدة')),
                ('ai_program', models.JSONField(blank=True, default=dict, verbose_name='البرنامج الإذاعي المولّد')),
                ('ai_status', models.CharField(choices=[('none', 'بدون محتوى ذكي'), ('pending', 'مسودة بانتظار المراجعة'), ('approved', 'تمت مراجعته واعتماده')], default='none', max_length=20, verbose_name='حالة المحتوى الذكي')),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('ai_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجع المحتوى الذكي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_radio_entries', to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('participants', models.ManyToManyField(blank=True, related_name='school_radio_entries', to='school.student', verbose_name='الطلبة المشاركون')),
                ('presenters', models.ManyToManyField(blank=True, related_name='presented_school_radio_entries', to='school.student', verbose_name='الطلبة المقدّمون')),
            ],
            options={
                'verbose_name': 'إذاعة مدرسية',
                'verbose_name_plural': 'ملف الإذاعة المدرسية',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRadioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300, verbose_name='اسم الملف')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('google_drive_file_id', models.CharField(blank=True, max_length=200, verbose_name='معرّف ملف Google Drive')),
                ('google_drive_url', models.TextField(blank=True, verbose_name='رابط الملف في Drive')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='open_learning.schoolradioentry', verbose_name='سجل الإذاعة')),
            ],
            options={
                'verbose_name': 'ملف إذاعة مدرسية',
                'verbose_name_plural': 'ملفات الإذاعة المدرسية',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.RunPython(enable_radio_rls, disable_radio_rls),
    ]
